variables:
  IMAGE_NAME_FRONT: traefik2025front
  FILE_NAME_FRONT: fsci2025-traefik_frontend
  VITE_API_URL_DEV: http://traefik2025-backend-service:8000
  VITE_API_URL_STAGING: https://api.dashboard.localhost
  VITE_API_URL_PROD: https://api.fsci-rncp2025.com

build_frontend_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags: [rncp,aws,k8s]
  before_script:
    - while ! docker info > /dev/null 2>&1; do sleep 1; done
    - docker info
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t $IMAGE_REPO/$IMAGE_NAME_FRONT:$CI_COMMIT_SHORT_SHA ./frontend
    - docker save $IMAGE_REPO/$IMAGE_NAME_FRONT:$CI_COMMIT_SHORT_SHA > $FILE_NAME_FRONT.tar
  artifacts:
    paths:
      - $FILE_NAME_FRONT.tar
  rules:
    - if: $CI_COMMIT_TAG
    - changes:
        - frontend/**
        - frontend/.gitlab-ci.yml
        - ci-template.yml
        - .gitlab-ci.yml

push_frontend_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  tags: [rncp,aws,k8s]
  script:
    - docker load < $FILE_NAME_FRONT.tar
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_REPO/$IMAGE_NAME_FRONT:$CI_COMMIT_SHORT_SHA
  dependencies: [build_frontend_image]
  needs: [build_frontend_image]
  rules:
    - if: $CI_COMMIT_TAG
    - changes:
        - frontend/**
        - frontend/.gitlab-ci.yml
        - ci-template.yml
        - .gitlab-ci.yml

stop_deploy_frontend_dev:
  extends: .stop_template
  stage: deploy_dev
  environment:
    name: dev-$CI_COMMIT_REF_NAME
    action: stop
  variables:
    namespace: $KUBE_NAMESPACE_dev

stop_deploy_frontend_staging:
  extends: .stop_template
  stage: deploy_staging
  environment:
    name: staging
    action: stop
  variables:
    namespace: $KUBE_NAMESPACE_staging

stop_deploy_frontend_prod:
  extends: .stop_template
  stage: deploy_prod
  environment:
    name: prod
    action: stop
  variables:
    namespace: $KUBE_NAMESPACE_prod

deploy_frontend_dev:
  extends: .deploy_template
  stage: deploy_dev
  variables:
    namespace: $KUBE_NAMESPACE_dev
    imagename: $IMAGE_NAME_FRONT
    vite_api_url: $VITE_API_URL_DEV
  environment:
    name: dev-$CI_COMMIT_REF_NAME
    on_stop: stop_deploy_frontend_dev
  needs: [push_frontend_image]
  when: on_success
  rules:
    - if: $CI_COMMIT_TAG
    - changes:
        - frontend/**
        - frontend/.gitlab-ci.yml
        - ci-template.yml
        - .gitlab-ci.yml

deploy_frontend_staging:
  extends: .deploy_template
  stage: deploy_staging
  variables:
    namespace: $KUBE_NAMESPACE_staging
    imagename: $IMAGE_NAME_FRONT
    vite_api_url: $VITE_API_URL_STAGING
  environment:
    name: staging
    on_stop: stop_deploy_frontend_staging
  needs: [deploy_frontend_dev]
  when: manual
  rules:
    - if: $CI_COMMIT_TAG
    - changes:
        - frontend/**
        - frontend/.gitlab-ci.yml
        - ci-template.yml
        - .gitlab-ci.yml

deploy_frontend_prod:
  extends: .deploy_template
  stage: deploy_prod
  variables:
    namespace: $KUBE_NAMESPACE_prod
    imagename: $IMAGE_NAME_FRONT
    vite_api_url: $VITE_API_URL_PROD
  environment:
    name: prod
    on_stop: stop_deploy_frontend_prod
  needs: [deploy_frontend_staging]
  when: manual
  rules:
    - if: $CI_COMMIT_TAG
    - changes:
        - frontend/**
        - frontend/.gitlab-ci.yml
        - ci-template.yml
        - .gitlab-ci.yml